# Generated by Django 3.0.8 on 2020-07-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record250',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_indicator', models.CharField(choices=[('100', '100'), ('250', '250'), ('550', '550')], max_length=3)),
                ('nmi', models.CharField(max_length=10)),
                ('nmi_configuration', models.CharField(max_length=240)),
                ('register_id', models.CharField(max_length=10)),
                ('nmi_suffix', models.CharField(max_length=2)),
                ('mdm_data_stream_identifier', models.CharField(max_length=2)),
                ('meter_serial_number', models.CharField(max_length=12)),
                ('direction_indicator', models.CharField(choices=[('I', 'Import'), ('E', 'Export')], max_length=1)),
                ('previous_register_read', models.CharField(max_length=15)),
                ('previous_register_read_datetime', models.DateTimeField()),
                ('previous_quality_method', models.CharField(max_length=3)),
                ('previous_reason_code', models.IntegerField()),
                ('previous_reason_description', models.CharField(max_length=240)),
                ('current_register_read', models.CharField(max_length=15)),
                ('current_register_read_datetime', models.DateTimeField()),
                ('current_quality_method', models.CharField(max_length=3)),
                ('current_reason_code', models.IntegerField()),
                ('current_reason_description', models.CharField(max_length=240)),
                ('quantity', models.IntegerField()),
                ('uom', models.CharField(max_length=5)),
                ('next_scheduled_read_date', models.DateField()),
                ('update_datetime', models.DateTimeField()),
                ('msats_load_datetime', models.DateTimeField()),
                ('nemfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record250', to='reader.NemFile')),
            ],
            options={
                'unique_together': {('nemfile', 'record_indicator')},
            },
        ),
        migrations.CreateModel(
            name='Record550',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_indicator', models.CharField(choices=[('100', '100'), ('250', '250'), ('550', '550')], max_length=3)),
                ('previous_trans_code', models.CharField(max_length=1)),
                ('previous_ret_service_order', models.CharField(max_length=15)),
                ('current_trans_code', models.CharField(max_length=1)),
                ('current_ret_service_order', models.CharField(max_length=15)),
                ('nemfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record550', to='reader.NemFile')),
                ('record250', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record550', to='reader.Record250')),
            ],
            options={
                'unique_together': {('nemfile', 'record_indicator')},
            },
        ),
        migrations.CreateModel(
            name='Record100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_indicator', models.CharField(choices=[('100', '100'), ('250', '250'), ('550', '550')], max_length=3)),
                ('version_header', models.CharField(choices=[('NEM13', 'NEM13')], max_length=5)),
                ('datetime', models.DateTimeField()),
                ('from_participant', models.CharField(max_length=10)),
                ('to_participant', models.CharField(max_length=10)),
                ('nemfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record100', to='reader.NemFile')),
            ],
            options={
                'unique_together': {('nemfile', 'record_indicator')},
            },
        ),
    ]
