# Generated by Django 3.0.8 on 2020-07-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_record100_record250_record550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('nemfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reader.NemFile')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('reader_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='reader.ReaderRun')),
            ],
        ),
    ]
