# Generated by Django 3.0.8 on 2020-07-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_readererror_readerrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='nemfile',
            name='path',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readerrun',
            name='number_invalid_records',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readerrun',
            name='total_records',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
