# Generated by Django 3.0.8 on 2020-07-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_auto_20200704_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerrun',
            name='number_invalid_records',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='readerrun',
            name='total_records',
            field=models.IntegerField(blank=True),
        ),
    ]
