# Generated by Django 3.0.8 on 2020-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_auto_20200705_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerrun',
            name='number_invalid_records',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='readerrun',
            name='total_records',
            field=models.IntegerField(null=True),
        ),
    ]
