# Generated by Django 3.0.8 on 2020-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_auto_20200705_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record250',
            name='current_quality_method',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='current_reason_description',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='current_register_read',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='current_register_read_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='mdm_data_stream_identifier',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='msats_load_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='next_scheduled_read_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='previous_quality_method',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='previous_reason_description',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='uom',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='record250',
            name='update_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='record550',
            name='current_ret_service_order',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='record550',
            name='current_trans_code',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='record550',
            name='previous_ret_service_order',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='record550',
            name='previous_trans_code',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
