# Generated by Django 3.0.8 on 2020-07-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_auto_20200705_0836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record250',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='record550',
            unique_together=set(),
        ),
    ]
