# Generated by Django 3.0.8 on 2020-07-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_auto_20200705_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='NemFileError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('nemfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='reader.NemFile')),
            ],
        ),
    ]
